### ISSUE TITLE
assertion failure in push_interfaces_above()

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/omphalos#29]
```c
#0  0x00007ffff7693f25 in raise () from /usr/lib/libc.so.6i/index.php/Omphalos─╯
#1  0x00007ffff767d897 in abort () from /usr/lib/libc.so.6────pci:0000:04:00.0─╯
#2  0x00007ffff767d767 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff768c526 in __assert_fail () from /usr/lib/libc.so.6
#4  0x000055555557792f in push_interfaces_above (pusher=<optimized out>, 
    rows=<optimized out>, cols=<optimized out>, delta=<optimized out>)
    at src/ui/ncurses/core.c:451
#5  push_interfaces_above (pusher=<optimized out>, rows=<optimized out>, 
    cols=<optimized out>, delta=<optimized out>) at src/ui/ncurses/core.c:448
#6  0x0000555555577fbf in resize_iface (rb=rb@entry=0x5555696e5ed0)
    at src/ui/ncurses/core.c:560
#7  0x000055555557993f in host_callback_locked (i=<optimized out>, 
    l2=<optimized out>, l3=0x7fffc400bfc0) at src/ui/ncurses/core.c:954
#8  0x000055555557ce68 in host_callback (i=0x555555717758 <interfaces+14232>, 
    l2=0x7fffc400dcf0, l3=0x7fffc400bfc0) at src/ui/ncurses/ncurses.c:595
#9  0x000055555555f4ba in wname_l3host_absolute (
    i=0x555555717758 <interfaces+14232>, l2=0x7fffc400dcf0, l3=0x7fffc400bfc0, 
    name=<optimized out>, nlevel=NAMING_LEVEL_NXDOMAIN)
    at src/omphalos/netaddrs.c:178
#10 0x0000555555568143 in offer_wresolution (fam=<optimized out>, 
    addr=addr@entry=0x7fffdd439cd0, 
    name=name@entry=0x555555583b58 L"address unknown", 
    nlevel=nlevel@entry=NAMING_LEVEL_NXDOMAIN, nsfam=nsfam@entry=2, 
    nameserver=nameserver@entry=0x7fffdd439cb0) at src/omphalos/resolv.c:165
#11 0x000055555556b095 in handle_dns_packet (op=0x7fffdd439d90, 
    frame=0x7fffde41306c, len=33) at src/omphalos/dns.c:471
#12 0x0000555555568cfb in handle_udp_packet (op=0x7fffdd439d90, 
    frame=<optimized out>, len=<optimized out>) at src/omphalos/udp.c:44
#13 0x000055555556f232 in handle_ring_packet (
    iface=0x555555717758 <interfaces+14232>, fd=<optimized out>, 
    frame=0x7fffde413042, frame@entry=0x7fffde413000)
    at src/omphalos/psocket.c:254
#14 0x0000555555563849 in ring_packet_loop (pm=0x555569675cf0, 
    pm=0x555569675cf0) at src/omphalos/netlink.c:433
#15 psocket_thread (unsafe=0x555569675cf0) at src/omphalos/netlink.c:460
#16 psocket_thread (unsafe=0x555569675cf0) at src/omphalos/netlink.c:448
#17 0x00007ffff78284cf in start_thread () from /usr/lib/libpthread.so.0
#18 0x00007ffff77572d3 in clone () from /usr/lib/libc.so.6
```

**Comment by dankamongmen** [comment]
This happens when a focused panel not on the top line grows to fill said line, and delta comes in as 0. I've changed the assert to accept a 0 delta. The panel now grows properly, although if we go down from this tablet, there's a bit of cruft.

Since it's no longer breaking, I'm going to leave this fix to outcurses.
